-- Top 100 DJs from DJ Mag 2025
-- Insert top DJs with their genres

INSERT INTO djs (id, name, genre, email) VALUES
('dj-001', 'David Guetta', 'EDM', 'david.guetta@djmag.com'),
('dj-002', 'Martin Garrix', 'Progressive House', 'martin.garrix@djmag.com'),
('dj-003', 'Alok', 'Bass House', 'alok@djmag.com'),
('dj-004', 'Dimitri Vegas & Like Mike', 'Big Room', 'dvlm@djmag.com'),
('dj-005', 'Armin Van Buuren', 'Trance', 'armin@djmag.com'),
('dj-006', 'Timmy Trumpet', 'Melbourne Bounce', 'timmy.trumpet@djmag.com'),
('dj-007', 'FISHER', 'Tech House', 'fisher@djmag.com'),
('dj-008', 'Afrojack', 'Electro House', 'afrojack@djmag.com'),
('dj-009', 'Charlotte de Witte', 'Techno', 'charlotte.dewitte@djmag.com'),
('dj-010', 'Anyma', 'Melodic Techno', 'anyma@djmag.com'),
('dj-011', 'Vintage Culture', 'Tech House', 'vintage.culture@djmag.com'),
('dj-012', 'Peggy Gou', 'House', 'peggy.gou@djmag.com'),
('dj-013', 'Don Diablo', 'Future House', 'don.diablo@djmag.com'),
('dj-014', 'Steve Aoki', 'Electro House', 'steve.aoki@djmag.com'),
('dj-015', 'Hardwell', 'Big Room', 'hardwell@djmag.com'),
('dj-016', 'Calvin Harris', 'EDM', 'calvin.harris@djmag.com'),
('dj-017', 'Black Coffee', 'Afro House', 'black.coffee@djmag.com'),
('dj-018', 'W&W', 'Big Room', 'ww@djmag.com'),
('dj-019', 'Lost Frequencies', 'Deep House', 'lost.frequencies@djmag.com'),
('dj-020', 'Keinemusik', 'Melodic House', 'keinemusik@djmag.com'),
('dj-021', 'Tiësto', 'EDM', 'tiesto@djmag.com'),
('dj-022', 'Reinier Zonneveld', 'Techno', 'reinier.zonneveld@djmag.com'),
('dj-023', 'KSHMR', 'Big Room', 'kshmr@djmag.com'),
('dj-024', 'Alan Walker', 'Future Bass', 'alan.walker@djmag.com'),
('dj-025', 'Carl Cox', 'Techno', 'carl.cox@djmag.com'),
('dj-026', 'Oliver Heldens', 'Future House', 'oliver.heldens@djmag.com'),
('dj-027', 'Jamie Jones', 'Tech House', 'jamie.jones@djmag.com'),
('dj-028', 'R3hab', 'Electro House', 'r3hab@djmag.com'),
('dj-029', 'Nicky Romero', 'Progressive House', 'nicky.romero@djmag.com'),
('dj-030', 'Claptone', 'House', 'claptone@djmag.com'),
('dj-031', 'Skrillex', 'Dubstep', 'skrillex@djmag.com'),
('dj-032', 'Vini Vici', 'Psytrance', 'vini.vici@djmag.com'),
('dj-033', 'Fred again..', 'House', 'fred.again@djmag.com'),
('dj-034', 'Swedish House Mafia', 'Progressive House', 'shm@djmag.com'),
('dj-035', 'Joel Corry', 'House', 'joel.corry@djmag.com'),
('dj-036', 'Indira Paganotto', 'Techno', 'indira.paganotto@djmag.com'),
('dj-037', 'Eric Prydz', 'Progressive House', 'eric.prydz@djmag.com'),
('dj-038', 'Amelie Lens', 'Techno', 'amelie.lens@djmag.com'),
('dj-039', 'Paul van Dyk', 'Trance', 'paul.vandyk@djmag.com'),
('dj-040', 'DJ Snake', 'Trap', 'dj.snake@djmag.com'),
('dj-041', 'Dom Dolla', 'Tech House', 'dom.dolla@djmag.com'),
('dj-042', 'Marshmello', 'Future Bass', 'marshmello@djmag.com'),
('dj-043', 'The Martinez Brothers', 'House', 'martinez.brothers@djmag.com'),
('dj-044', 'Zedd', 'Electro House', 'zedd@djmag.com'),
('dj-045', 'Bassjackers', 'Electro House', 'bassjackers@djmag.com'),
('dj-046', 'John Summit', 'Tech House', 'john.summit@djmag.com'),
('dj-047', 'Quintino', 'Big Room', 'quintino@djmag.com'),
('dj-048', 'Michael Bibi', 'Tech House', 'michael.bibi@djmag.com'),
('dj-049', 'Boris Brejcha', 'Minimal Techno', 'boris.brejcha@djmag.com'),
('dj-050', 'Korolova', 'Techno', 'korolova@djmag.com'),
('dj-051', 'Alesso', 'Progressive House', 'alesso@djmag.com'),
('dj-052', 'James Hype', 'Tech House', 'james.hype@djmag.com'),
('dj-053', 'Maddix', 'Big Room', 'maddix@djmag.com'),
('dj-054', 'HUGEL', 'House', 'hugel@djmag.com'),
('dj-055', 'Solomun', 'Deep House', 'solomun@djmag.com'),
('dj-056', 'Mochakk', 'Tech House', 'mochakk@djmag.com'),
('dj-057', 'Lilly Palmer', 'Techno', 'lilly.palmer@djmag.com'),
('dj-058', 'Nora En Pure', 'Deep House', 'nora.enpure@djmag.com'),
('dj-059', 'ATB', 'Trance', 'atb@djmag.com'),
('dj-060', 'Deborah De Luca', 'Techno', 'deborah.deluca@djmag.com'),
('dj-061', 'Above & Beyond', 'Trance', 'aboveandbeyond@djmag.com'),
('dj-062', 'Sara Landry', 'Hard Techno', 'sara.landry@djmag.com'),
('dj-063', 'Nervo', 'Progressive House', 'nervo@djmag.com'),
('dj-064', 'Sub Zero Project', 'Hardstyle', 'subzeroproject@djmag.com'),
('dj-065', 'Kölsch', 'Techno', 'kolsch@djmag.com'),
('dj-066', 'Lucas & Steve', 'Future House', 'lucas.steve@djmag.com'),
('dj-067', 'Nico Moreno', 'Hard Techno', 'nico.moreno@djmag.com'),
('dj-068', 'GORDO', 'Tech House', 'gordo@djmag.com'),
('dj-069', 'PAWSA', 'Tech House', 'pawsa@djmag.com'),
('dj-070', 'The Chainsmokers', 'EDM', 'chainsmokers@djmag.com'),
('dj-071', 'Liu', 'Techno', 'liu@djmag.com'),
('dj-072', 'Mike Williams', 'Future House', 'mike.williams@djmag.com'),
('dj-073', 'ARTBAT', 'Melodic Techno', 'artbat@djmag.com'),
('dj-074', 'KAAZE', 'Big Room', 'kaaze@djmag.com'),
('dj-075', 'Miss Monique', 'Progressive House', 'miss.monique@djmag.com'),
('dj-076', 'Burak Yeter', 'Deep House', 'burak.yeter@djmag.com'),
('dj-077', 'Mau P', 'Tech House', 'mau.p@djmag.com'),
('dj-078', 'Le Twins', 'Techno', 'le.twins@djmag.com'),
('dj-079', 'I Hate Models', 'Industrial Techno', 'i.hate.models@djmag.com'),
('dj-080', 'Marnik', 'Big Room', 'marnik@djmag.com'),
('dj-081', 'Chris Stussy', 'House', 'chris.stussy@djmag.com'),
('dj-082', 'Deadmau5', 'Progressive House', 'deadmau5@djmag.com'),
('dj-083', 'WUKONG', 'Techno', 'wukong@djmag.com'),
('dj-084', 'Fedde Le Grand', 'Electro House', 'fedde.legrand@djmag.com'),
('dj-085', 'Ferry Corsten', 'Trance', 'ferry.corsten@djmag.com'),
('dj-086', 'Plastik Funk', 'Electro House', 'plastik.funk@djmag.com'),
('dj-087', 'DubVision', 'Progressive House', 'dubvision@djmag.com'),
('dj-088', 'B Jones', 'Tech House', 'b.jones@djmag.com'),
('dj-089', 'Giuseppe Ottaviani', 'Trance', 'giuseppe.ottaviani@djmag.com'),
('dj-090', 'Cuebrick', 'Future House', 'cuebrick@djmag.com'),
('dj-091', 'Mariana Bo', 'Techno', 'mariana.bo@djmag.com'),
('dj-092', 'MEDUZA', 'Deep House', 'meduza@djmag.com'),
('dj-093', 'Fantasm', 'Techno', 'fantasm@djmag.com'),
('dj-094', 'VINAI', 'Big Room', 'vinai@djmag.com'),
('dj-095', 'Chris Lake', 'Tech House', 'chris.lake@djmag.com'),
('dj-096', 'Faustix', 'Future House', 'faustix@djmag.com'),
('dj-097', 'Honey Dijon', 'House', 'honey.dijon@djmag.com'),
('dj-098', 'Nils van Zandt', 'Hands Up', 'nils.vanzandt@djmag.com'),
('dj-099', 'Topic', 'Deep House', 'topic@djmag.com'),
('dj-100', 'Marlon Hoffstadt', 'House', 'marlon.hoffstadt@djmag.com')
ON CONFLICT (id) DO NOTHING;
